admins: []
forwards:
- source: https://t.me/sexyboy2019_TH
  dest:
  - -1001753504711
  offset: 16200
  end: 140063
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins:
  filter:
    text:
      blacklist:
      - nope
