admins: []
forwards:
- source: -1001742863201
  dest:
  - 1631273213

show_forwarded_from: false

live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins:
  filter:
    text:
      blacklist:
      - nope
